repos:
  - repo: https://github.com/pre-commit/mirrors-pyright
    rev: v1.1.408
    hooks:
      - id: pyright
        args: ["--project", "backend/pyrightconfig.json"]
  - repo: https://github.com/pycqa/pylint
    rev: v3.3.1
    hooks:
      - id: pylint
        args: ["--rcfile=backend/.pylintrc", "backend/app"]
  - repo: https://github.com/pycqa/pycodestyle
    rev: 2.12.1
    hooks:
      - id: pycodestyle
        args: ["--config=backend/setup.cfg", "backend/app"]
