repos:
  - repo: local
    hooks:
      - id: pyright
        name: pyright
        entry: backend/.venv/bin/pyright
        language: system
        args: ["--project", "backend/pyrightconfig.json"]
        files: ^backend/app/
        types: [python]
      - id: pylint
        name: pylint
        entry: backend/.venv/bin/pylint
        language: system
        args: ["--rcfile=backend/.pylintrc", "backend/app"]
        files: ^backend/app/
        exclude: ^backend/app/generated/
        types: [python]
      - id: pycodestyle
        name: pycodestyle
        entry: backend/.venv/bin/pycodestyle
        language: system
        args: ["--config=backend/setup.cfg", "backend/app"]
        files: ^backend/app/
        exclude: ^backend/app/generated/
        types: [python]
